export const SEARCH_ARTISTS = "SEARCH_ARTISTS";
export const SEARCH_ARTISTS_START = "SEARCH_ARTISTS_START";
export const SEARCH_ARTISTS_SUCCESS = "SEARCH_ARTISTS_SUCCESS";
export const SEARCH_ARTISTS_FAIL = "SEARCH_ARTISTS_FAIL";
